name: cytools-dev
channels:
  - conda-forge
dependencies:
  # CYTools dependencies
  - python
  - numba
  - numpy
  - normaliz
  - scipy
  - cvxopt
  - python-flint
  - ppl
  - joblib
  - tqdm
  - requests
  - osqp
  - pytest
  - pip
  - pip:
    - ortools
    - mosek
    - triangulumancer
    - pypalp
    - qpsolvers
    - cygv
    - regfans
    # Editable CYTools installation
    - -e .
  # Common useful tools
  - jupyterlab
  - matplotlib
  - plotly
  - ipywidgets
  - anywidget
  # Uncomment the following lines for additional tools
  # - sage